[build]

command = "npm run prod"
publish = "build_production"
environment = { PHP_VERSION = "7.4", NODE_VERSION = "12.16.1" }

[[redirects]]
  from = "/api/module/json/*"
  to = "http://193.242.154.229/api/module/json/:splat"
  force = true
  headers = {Access-Control-Allow-Origin = "*", Access-Control-Allow-Methods = "POST"}
  
[[redirects]]
  from = "/XML/*"
  to = "http://193.242.154.229/XML/:splat"
  force = true
  headers = {Access-Control-Allow-Origin = "*", Access-Control-Allow-Methods = "POST"}
