[build]

command = "npm run prod"
publish = "build_production"
environment = { PHP_VERSION = "7.4", NODE_VERSION = "12.16.1" }

[[redirects]]
  from = "/api/*"
  to = "http://rockradio.si/api/:splat"
  status = 200
  force = true
